name: Build and Release macOS App

on:
  push:
    tags:
      - 'v*.*.*' # Matches any semantic version tag (e.g., v0.1.1, v0.1.1-alpha)
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to latest version

      - name: Set up Go
        uses: actions/setup-go@v5 # Updated to latest version
        with:
          go-version: '1.21'

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Build macOS App
        run: |
          chmod +x build_macos.sh
          ./build_macos.sh
        env:
          GOOS: darwin
          GOARCH: amd64

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2 # Updated to latest version
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: OpenRouterProxy.dmg
          draft: false
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload DMG as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenRouterProxy-macOS
          path: OpenRouterProxy.dmg
          retention-days: 7